spring.application.name=ShopScope
spring.security.user.name=admin
spring.security.user.password=admin

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/shopscopedb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration (Secret must be at least 256 bits / 32 characters for HS256)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-expiration-ms=86400000
jwt.refresh-expiration-ms=604800000

# Ollama Cloud API (OpenAI Compatible Endpoint)
spring.ai.openai.base-url=https://ollama.com
spring.ai.openai.api-key=012932f196184aa28111e5d1ca5b5fff.6x3yptRzm_M3rB-o-d5FqO4S
spring.ai.openai.chat.options.model=gemma4:31b
spring.ai.openai.chat.options.temperature=0.4