package com.ShopScope.ShopScope.ai;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@Service
public class AgentChatService {

    private static final Logger log = LoggerFactory.getLogger(AgentChatService.class);
    private final ChatClient chatClient;
    private final ShopAssistantTools tools;

    private final Map<String, List<String>> conversationHistories = new ConcurrentHashMap<>();

    public AgentChatService(ChatClient chatClient, ShopAssistantTools tools) {
        this.chatClient = chatClient;
        this.tools = tools;
    }

    public String determineGreeting(String timeZone) {
        ZoneId zoneId;
        try {
            zoneId = (timeZone != null && !timeZone.isBlank()) ? ZoneId.of(timeZone) : ZoneId.systemDefault();
        } catch (Exception e) {
            zoneId = ZoneId.systemDefault();
        }
        LocalTime time = ZonedDateTime.now(zoneId).toLocalTime();
        int hour = time.getHour();
        if (hour >= 5 && hour < 12) {
            return "Good morning";
        } else if (hour >= 12 && hour < 17) {
            return "Good afternoon";
        } else {
            return "Good evening";
        }
    }

    public String processUserMessage(String userMessage, Long userId, String conversationId, String timeZone) {
        Long safeUserId = userId != null ? userId : 1L;
        String safeSessionId = (conversationId != null && !conversationId.isBlank()) ? conversationId : ("user-" + safeUserId);

        List<String> history = conversationHistories.computeIfAbsent(safeSessionId, k -> new ArrayList<>());
        boolean isFirstMessage = history.isEmpty();
        String greeting = determineGreeting(timeZone);

        String systemPrompt = String.format("""
            You are the ShopScope shopping assistant.
            Customer ID: %d.

            Behavioral Guidelines:
            1. GREETING RULE:
               %s
               NEVER start your message with a greeting if the user has already sent messages or an inquiry.
            2. ADD TO CART:
               - When the user selects or agrees to an item, call `addToCart` with the exact product ID or product title.
               - Keep any `[CART_ACTION:ADD:...]` tag generated by the tool intact in your response.
               - Confirm the item added and ask: "Would you like to proceed to checkout or look for anything else?"
            3. CHECKOUT TRANSITION:
               - If the user says 'checkout', 'proceed to checkout', or wants to complete their cart purchase on the checkout page, output:
                 "Heading to checkout now! [ACTION:OPEN_CHECKOUT]"
               - If the user explicitly asks you to place the order right now in chat, call `placeOrder` with Customer ID %d and the discussed product.
            4. ACCURACY:
               - Never place an order for or add an iPhone or any other product unless the user explicitly requested it. Always refer to the exact product the user requested.
            """,
            safeUserId,
            isFirstMessage 
                ? "This is the very first turn. Greet the user: \"" + greeting + "! What would you like to purchase today?\""
                : "This conversation is ongoing. DO NOT greet or welcome the user again.",
            safeUserId
        );

        StringBuilder conversationContext = new StringBuilder();
        if (!history.isEmpty()) {
            conversationContext.append("Previous dialogue:\n");
            for (String turn : history) {
                conversationContext.append(turn).append("\n");
            }
            conversationContext.append("\nUser: ").append(userMessage);
        } else {
            conversationContext.append(userMessage);
        }

        try {
            String assistantResponse = chatClient.prompt()
                    .system(systemPrompt)
                    .user(conversationContext.toString())
                    .tools(tools)
                    .call()
                    .content();

            history.add("User: " + userMessage);
            history.add("Assistant: " + assistantResponse);
            if (history.size() > 12) {
                history.subList(0, history.size() - 12).clear();
            }

            return assistantResponse;
        } catch (Exception ex) {
            log.error("Error executing Ollama Cloud chat agent: ", ex);
            return "I am currently unable to process that. Please ensure your Ollama Cloud API key is valid and has access to the configured model.";
        }
    }
}