plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.ShopScope'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator:3.2.5'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.5'
    // implementation 'org.springframework.boot:spring-boot-starter-flyway:3.2.5'
    implementation 'org.springframework.boot:spring-boot-starter-security:3.2.5'
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.2.5'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.2.5'
    
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.2.5'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}